import React, { useEffect, useRef } from 'react';
import { MapPin } from 'lucide-react';

const STATE_CENTERS = {
  'Uttar Pradesh': [26.85, 80.95], 'Maharashtra': [19.75, 75.7], 'Karnataka': [15.3, 75.7], 'Tamil Nadu': [11.0, 78.3], 'Gujarat': [22.3, 71.8], 'Rajasthan': [27.0, 74.2], 'Madhya Pradesh': [23.5, 78.0], 'Bihar': [25.8, 85.3], 'Odisha': [20.2, 84.4], 'West Bengal': [23.0, 87.8],
};
function coords(p) { if (Number.isFinite(Number(p.latitude)) && Number.isFinite(Number(p.longitude))) return [Number(p.latitude), Number(p.longitude)]; const c=STATE_CENTERS[p.state]||[22.5,78.9]; let h=0; const s=`${p.state??''}:${p.district??''}`; for(let i=0;i<s.length;i++) h=(h*31+s.charCodeAt(i))|0; return [c[0]+((h%80)-40)/100,c[1]+((((h/80)|0)%80)-40)/100]; }
function riskColor(r){ return r>=70?'#dc2626':r>=40?'#d97706':'#059669'; }
export function GISMap({projects=[],selectedProjectId,onSelectProject,selectedRisk,baselineRisk}) {
 const mapRef=useRef(null), instanceRef=useRef(null), markersRef=useRef([]);
 useEffect(()=>{ const load=async()=>{ if(!window.L){await new Promise((res,rej)=>{const s=document.createElement('script');s.src='https://unpkg.com/leaflet@1.9.4/dist/leaflet.js';s.onload=res;s.onerror=rej;document.head.appendChild(s);});} if(!mapRef.current||instanceRef.current)return; const L=window.L; const map=L.map(mapRef.current,{zoomControl:true}).setView([22.5,78.9],5); L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'&copy; OpenStreetMap contributors',maxZoom:19}).addTo(map); instanceRef.current=map; }; load().catch(()=>{}); return()=>{if(instanceRef.current){instanceRef.current.remove();instanceRef.current=null;}};},[]);
 useEffect(()=>{const map=instanceRef.current;if(!map||!window.L)return;markersRef.current.forEach(m=>m.remove());markersRef.current=[];projects.forEach(p=>{const [lat,lng]=coords(p),id=p.project_id??p.id,isSelected=id===selectedProjectId,hasRisk=isSelected&&Number.isFinite(Number(selectedRisk)),risk=hasRisk?Number(selectedRisk):null,color=hasRisk?riskColor(risk):'#64748b';const m=window.L.circleMarker([lat,lng],{radius:isSelected?10:7,color,fillColor:color,fillOpacity:.8,weight:2}).addTo(map);m.bindPopup(`<strong>${id??'Project'}</strong><br/>${p.district??''}, ${p.state??''}${hasRisk?`<br/>Risk: ${risk.toFixed(1)}/100`:'<br/>Risk: Select project to calculate'}<br/>Stage: ${p.acquisition_stage??'—'}${hasRisk&&Number.isFinite(Number(baselineRisk))?`<br/>Baseline: ${Number(baselineRisk).toFixed(1)}/100<br/><strong>What-If: ${risk.toFixed(1)}/100</strong>`:''}`);m.on('click',()=>onSelectProject?.(id));markersRef.current.push(m);});const selected=projects.find(p=>(p.project_id??p.id)===selectedProjectId);if(selected){const [lat,lng]=coords(selected);map.setView([lat,lng],Math.max(map.getZoom(),9));}},[projects,selectedProjectId,selectedRisk,baselineRisk,onSelectProject]);
 const hasSimulation=Number.isFinite(Number(selectedRisk))&&Number.isFinite(Number(baselineRisk));
 return <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-200 px-4 py-3"><div><div className="flex items-center gap-2 font-bold text-slate-900"><MapPin className="h-4 w-4 text-blue-600"/>Project GIS Map</div><p className="mt-0.5 text-[11px] text-slate-500">OpenStreetMap • synthetic/demo coordinates until official GIS data is available</p></div>{hasSimulation&&<span className="rounded-full bg-amber-50 px-2.5 py-1 text-[10px] font-semibold text-amber-700">What-If active</span>}</div><div ref={mapRef} className="h-[460px] w-full"/></section>;
}
